import type { Metadata } from "next";
import { EMAILS } from "@kestrel/shared/constants";

export const metadata: Metadata = {
  title: "Terms of Service — Kestrel",
  description: "Terms of service for the Kestrel platform.",
};

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-screen-2xl px-4 py-24 sm:px-6 lg:px-8 2xl:px-12">
      <div className="rounded-2xl border border-border-subtle/60 bg-surface/70 p-8 shadow-sm backdrop-blur-xl sm:p-12">
        <h1 className="font-display text-4xl text-ink sm:text-5xl">
          Terms of Service
        </h1>
        <p className="mt-6 text-sm text-text-muted">
          Last updated: 6 April 2026
        </p>

        <div className="mt-12 space-y-10 text-text-secondary leading-relaxed">
          {/* 1 */}
          <section>
            <h2 className="font-display text-xl text-ink">1. About these terms</h2>
            <p className="mt-3">
              These terms of service (&ldquo;Terms&rdquo;) form a legally binding
              agreement between you and OnKestrel Limited, a company registered in
              England (company number pending), with its registered office in
              Newcastle-upon-Tyne (&ldquo;Kestrel&rdquo;, &ldquo;we&rdquo;,
              &ldquo;us&rdquo;). By accessing or using the Kestrel platform at
              any of its web addresses, you agree to be bound by these Terms. If
              you do not agree, you must not use the platform.
            </p>
          </section>

          {/* 2 */}
          <section>
            <h2 className="font-display text-xl text-ink">2. What Kestrel is</h2>
            <p className="mt-3">
              Kestrel is an online platform that provides business tools and a
              structured communication venue for resolving commercial disputes.
              Our services include free document generators, contract templates,
              late payment calculators, and a dispute resolution communication
              system.
            </p>
          </section>

          {/* 3 */}
          <section>
            <h2 className="font-display text-xl text-ink">3. What Kestrel is not</h2>
            <div className="mt-3 space-y-3">
              <p>
                <strong className="text-ink">Kestrel does not provide legal
                advice.</strong> Nothing on this platform, in our tools, templates,
                generated documents, or communications constitutes legal advice,
                legal representation, or a solicitor-client relationship.
              </p>
              <p>
                Kestrel does not act as a mediator, arbitrator, adjudicator, or
                legal representative. We facilitate structured communication
                between parties — we do not determine the merits of any claim,
                make binding decisions, or take sides.
              </p>
              <p>
                You should always seek independent professional legal advice for
                your specific circumstances. We strongly recommend having
                important agreements and documents reviewed by a qualified
                solicitor before relying on them.
              </p>
            </div>
          </section>

          {/* 4 */}
          <section>
            <h2 className="font-display text-xl text-ink">4. Free tools</h2>
            <div className="mt-3 space-y-3">
              <p>
                Our free tools (calculators, letter generators, contract
                templates, terms and conditions generators, handshake agreements,
                and milestone trackers) are provided for general informational
                purposes only. They are designed around the laws of England and
                Wales and may not be suitable for other jurisdictions.
              </p>
              <p>
                While we take reasonable care to ensure our templates and
                calculations are accurate, they are general-purpose tools and
                may not be appropriate for your specific situation. We make no
                guarantee that any document generated by our tools will be
                legally enforceable, complete, or fit for your particular
                purpose.
              </p>
              <p>
                You use the output of our free tools entirely at your own risk.
              </p>
            </div>
          </section>

          {/* 5 */}
          <section>
            <h2 className="font-display text-xl text-ink">5. Dispute resolution service</h2>
            <div className="mt-3 space-y-3">
              <p>
                Our dispute resolution service provides a structured
                communication channel between parties. Both parties must agree to
                use the platform. We do not guarantee any particular outcome and
                accept no responsibility for the outcome of any dispute.
              </p>
              <p>
                All submissions, evidence, and communications made through the
                dispute resolution service are the sole responsibility of the
                party that submits them. Kestrel does not verify the accuracy,
                truthfulness, or completeness of any information submitted by
                users.
              </p>
              <p>
                Use of the Kestrel dispute resolution service does not prevent
                either party from pursuing other remedies, including court
                proceedings, at any time.
              </p>
            </div>
          </section>

          {/* 6 */}
          <section>
            <h2 className="font-display text-xl text-ink">6. Accounts and security</h2>
            <div className="mt-3 space-y-3">
              <p>
                You are responsible for maintaining the confidentiality of your
                account credentials and for all activity that occurs under your
                account. You must provide accurate and complete information when
                creating an account and keep it up to date.
              </p>
              <p>
                You must notify us immediately if you become aware of any
                unauthorised use of your account. We may suspend or terminate
                accounts that violate these Terms or are used for fraudulent or
                abusive purposes.
              </p>
            </div>
          </section>

          {/* 7 */}
          <section>
            <h2 className="font-display text-xl text-ink">7. Acceptable use</h2>
            <div className="mt-3 space-y-3">
              <p>You agree not to use the platform to:</p>
              <ul className="ml-5 list-disc space-y-1.5 text-sm">
                <li>submit false, misleading, or fraudulent information;</li>
                <li>harass, threaten, or abuse other users;</li>
                <li>upload content that is unlawful, defamatory, or infringes
                  third-party intellectual property rights;</li>
                <li>attempt to gain unauthorised access to any part of the
                  platform or its infrastructure;</li>
                <li>use automated systems (bots, scrapers) to access the
                  platform without our written consent; or</li>
                <li>use the platform for any purpose that is unlawful under the
                  laws of England and Wales.</li>
              </ul>
            </div>
          </section>

          {/* 8 */}
          <section>
            <h2 className="font-display text-xl text-ink">
              8. Limitation of liability
            </h2>
            <div className="mt-3 space-y-3">
              <p>
                <strong className="text-ink">To the fullest extent permitted by
                law:</strong>
              </p>
              <ul className="ml-5 list-disc space-y-2 text-sm">
                <li>
                  The platform and all content, tools, templates, and documents
                  are provided on an &ldquo;as is&rdquo; and &ldquo;as
                  available&rdquo; basis without warranties of any kind, whether
                  express or implied, including but not limited to implied
                  warranties of merchantability, fitness for a particular
                  purpose, accuracy, or non-infringement.
                </li>
                <li>
                  We do not warrant that the platform will be uninterrupted,
                  error-free, secure, or free from viruses or other harmful
                  components.
                </li>
                <li>
                  OnKestrel Limited shall not be liable for any indirect,
                  incidental, special, consequential, or punitive damages,
                  including but not limited to loss of profits, loss of revenue,
                  loss of data, loss of business opportunity, or loss of
                  goodwill, however arising, whether in contract, tort
                  (including negligence), breach of statutory duty, or
                  otherwise, even if we have been advised of the possibility of
                  such damages.
                </li>
                <li>
                  Our total aggregate liability to you for all claims arising
                  from or related to your use of the platform shall not exceed
                  the greater of (a) the total fees paid by you to us in the
                  twelve (12) months preceding the event giving rise to the
                  claim, or (b) one hundred pounds sterling (&pound;100).
                </li>
                <li>
                  We accept no liability for any loss or damage arising from
                  your reliance on any document, template, calculation, or
                  other output generated by the platform. You are solely
                  responsible for verifying the suitability and accuracy of all
                  outputs for your purposes.
                </li>
                <li>
                  We accept no liability for the outcome of any dispute
                  conducted through the platform, or for any action or inaction
                  by any party to a dispute.
                </li>
              </ul>
              <p className="text-sm">
                Nothing in these Terms excludes or limits our liability for (a)
                death or personal injury caused by our negligence, (b) fraud or
                fraudulent misrepresentation, or (c) any other liability that
                cannot be excluded or limited under the laws of England and
                Wales.
              </p>
            </div>
          </section>

          {/* 9 */}
          <section>
            <h2 className="font-display text-xl text-ink">9. Indemnification</h2>
            <p className="mt-3">
              You agree to indemnify, defend, and hold harmless OnKestrel Limited
              and its officers, directors, employees, and agents from and against
              any claims, liabilities, damages, losses, and expenses (including
              reasonable legal fees) arising from or related to your use of the
              platform, your breach of these Terms, your violation of any
              applicable law, or the content you submit through the platform.
            </p>
          </section>

          {/* 10 */}
          <section>
            <h2 className="font-display text-xl text-ink">10. Intellectual property</h2>
            <div className="mt-3 space-y-3">
              <p>
                All intellectual property in the platform (including its design,
                code, brand, and template text) is owned by OnKestrel Limited or
                its licensors. You may not copy, modify, distribute, or create
                derivative works from any part of the platform without our prior
                written consent.
              </p>
              <p>
                Documents you generate using our tools are yours. We do not claim
                ownership of content you create or submit. However, by using our
                dispute resolution service, you grant us a limited licence to
                store and process your submissions for the purpose of providing
                the service.
              </p>
            </div>
          </section>

          {/* 11 */}
          <section>
            <h2 className="font-display text-xl text-ink">11. Paid services and refunds</h2>
            <div className="mt-3 space-y-3">
              <p>
                Certain features require a paid subscription or one-off payment.
                Prices are displayed before purchase and are subject to change
                with reasonable notice. All prices are in pounds sterling and
                inclusive of VAT where applicable.
              </p>
              <p>
                Subscription payments are non-refundable except where required by
                law. If you cancel a subscription, you retain access until the
                end of your current billing period. One-off dispute filing fees
                are non-refundable once the dispute process has been initiated.
              </p>
            </div>
          </section>

          {/* 12 */}
          <section>
            <h2 className="font-display text-xl text-ink">12. Termination</h2>
            <div className="mt-3 space-y-3">
              <p>
                You may close your account at any time through your account
                settings or by contacting us. We may suspend or terminate your
                account if you breach these Terms, with or without notice.
              </p>
              <p>
                On termination, your right to use the platform ceases
                immediately. Provisions that by their nature should survive
                termination (including limitation of liability, indemnification,
                and governing law) shall continue in full force and effect.
              </p>
            </div>
          </section>

          {/* 13 */}
          <section>
            <h2 className="font-display text-xl text-ink">13. Changes to these terms</h2>
            <p className="mt-3">
              We may update these Terms from time to time. Material changes will
              be communicated via email or a prominent notice on the platform. Your
              continued use of the platform after changes take effect constitutes
              acceptance of the revised Terms.
            </p>
          </section>

          {/* 14 */}
          <section>
            <h2 className="font-display text-xl text-ink">14. Governing law and jurisdiction</h2>
            <p className="mt-3">
              These Terms are governed by and construed in accordance with the
              laws of England and Wales. Any disputes arising from or in
              connection with these Terms shall be subject to the exclusive
              jurisdiction of the courts of England and Wales.
            </p>
          </section>

          {/* 15 */}
          <section>
            <h2 className="font-display text-xl text-ink">15. Severability</h2>
            <p className="mt-3">
              If any provision of these Terms is found to be invalid or
              unenforceable by a court of competent jurisdiction, the remaining
              provisions shall continue in full force and effect.
            </p>
          </section>

          {/* 16 */}
          <section>
            <h2 className="font-display text-xl text-ink">16. Contact</h2>
            <p className="mt-3">
              Questions about these terms? Contact us at{" "}
              <a
                href={`mailto:${EMAILS.hello}`}
                className="font-medium text-kestrel hover:text-kestrel-hover transition-colors"
              >
                {EMAILS.hello}
              </a>
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
