import { NextResponse } from "next/server";
import { createServiceClient } from "@kestrel/shared/supabase/service";
import { createHandshakeSchema } from "@/lib/handshake/schemas";
import { getResend } from "@kestrel/shared/email/client";
import { SITE_URL, EMAILS } from "@kestrel/shared/constants";
import { handshakeCreatedEmail } from "@/lib/email/templates/handshake-created";
import { publicRateLimit, applyRateLimit } from "@/lib/security/rate-limit";
import { validateOrigin } from "@/lib/security/csrf";

export async function POST(request: Request) {
  try {
    const originError = validateOrigin(request);
    if (originError) return originError;

    const rateLimitError = await applyRateLimit(request, publicRateLimit());
    if (rateLimitError) return rateLimitError;

    const body = await request.json();
    const parsed = createHandshakeSchema.safeParse(body);

    if (!parsed.success) {
      return NextResponse.json(
        { error: "Validation failed", issues: parsed.error.issues },
        { status: 400 },
      );
    }

    const { title, description, partyA, partyB, terms, includeDisputeClause } =
      parsed.data;

    const supabase = createServiceClient();

    // Insert the handshake (access_token is generated by the DB default)
    const { data: handshake, error: handshakeError } = await supabase
      .from("handshakes")
      .insert({
        title,
        description: description || null,
        party_a_name: partyA.name,
        party_a_email: partyA.email,
        party_a_business: partyA.businessName,
        party_b_name: partyB.name,
        party_b_email: partyB.email,
        party_b_business: partyB.businessName,
        includes_dispute_clause: includeDisputeClause,
        status: "pending",
      })
      .select("id, access_token")
      .single();

    if (handshakeError || !handshake) {
      console.error("Handshake insert error:", handshakeError);
      return NextResponse.json(
        { error: "Failed to create handshake" },
        { status: 500 },
      );
    }

    // Insert terms
    const termsToInsert = terms.map((term, index) => ({
      handshake_id: handshake.id,
      description: term.description,
      responsible_party: term.responsibleParty,
      deadline: term.deadline || null,
      amount:
        term.amount !== undefined && !Number.isNaN(term.amount)
          ? term.amount
          : null,
      sort_order: index,
    }));

    const { error: termsError } = await supabase
      .from("handshake_terms")
      .insert(termsToInsert);

    if (termsError) {
      console.error("Handshake terms insert error:", termsError);
      // Clean up the handshake if terms fail
      await supabase.from("handshakes").delete().eq("id", handshake.id);
      return NextResponse.json(
        { error: "Failed to create handshake terms" },
        { status: 500 },
      );
    }

    // Send email notification to Party B (fire-and-forget)
    const shareUrl = `${SITE_URL}/tools/handshake/${handshake.access_token}`;

    const email = handshakeCreatedEmail({
      partyBName: partyB.name,
      partyBBusiness: partyB.businessName,
      partyAName: partyA.name,
      partyABusiness: partyA.businessName,
      title,
      termCount: terms.length,
      shareUrl,
    });

    getResend()
      .emails.send({
        from: `Kestrel <${EMAILS.notifications}>`,
        to: partyB.email,
        subject: email.subject,
        html: email.html,
      })
      .catch((err) => {
        console.error("[handshake] Failed to send Party B notification:", err);
      });

    return NextResponse.json(
      { id: handshake.id, accessToken: handshake.access_token },
      { status: 201 },
    );
  } catch (error) {
    console.error("Handshake creation error:", error);
    return NextResponse.json(
      { error: "Internal server error" },
      { status: 500 },
    );
  }
}
